### ISSUE TITLE
Display plots in Juno

### ISSUE THREAD

**Issue by jzazo** [JuliaTeX/PGFPlots.jl#100]
Hi. Apparently there is no integration with Juno, is there? There is no mention in the documentation, but it would be a nice feature. Thanks.

**Comment by mykelk** [comment]
This works for me now. Please reopen this issue if you still have problems.

**Comment by jzazo** [comment]
What is the correct way to use it in Juno? I do the following, but nothing happens (well, the ouput of p is shown, but no plot):
```
using PGFPlots

x = 1:10
y = 1:10
p = Plots.Linear(x,y)
p
```

**Comment by mykelk** [comment]
It works for me:
![image](https://user-images.githubusercontent.com/6294079/46186476-a3452980-c293-11e8-8fb4-94c710a2f426.png)
Are you hitting shift-enter to execute those lines?

**Comment by jzazo** [comment]
Yes, I'm running with shift+enter. I have Atom 1.31.0, Ink 0.9.9, julia-client 0.7.7, Julia v0.6.4 on Ubuntu 18.04. Any idea why it might not be working?

![screen](https://user-images.githubusercontent.com/25750092/46187762-288c0680-c2b3-11e8-8234-8eb677d286a8.png)

**Comment by jzazo** [comment]
Yes, I'm running with shift+enter. I have Atom 1.31.0, Ink 0.9.9, julia-client 0.7.7, Julia v0.6.4 on Ubuntu 18.04. Any idea why it might not be working?

![screen](https://user-images.githubusercontent.com/25750092/46187891-e9aa8080-c2b3-11e8-8b51-5d90873a4c7e.png)

**Comment by mykelk** [comment]
Ah, okay. It works on Julia 1.0 for me. It looks like you are running 0.6. Are you able to update to Julia 0.7 or 1.0?

**Comment by jzazo** [comment]
I cannot update because some libraries I use have not updated yet. Hopefully they will manage soon. Anyway, if it is working moving forwards that's fine with me. I can save as pdf in  the meantime and open the file. Thank you.
