### ISSUE TITLE
Legend entries don't correspond to the desired plots

### ISSUE THREAD

**Issue by kunalmenda** [JuliaTeX/PGFPlots.jl#102]
Say I plot as follows:

```
ax = Axis()
push!(ax, Plots.Linear(x0,y0))
push!(ax, Plots.Linear(x1,y1), legendentry="leg1")
push!(ax, Plots.Linear(x2,y2), legendentry="leg2")
```

The resulting legend will have "leg1" and "leg2" correspond to the first and second lines respectively as opposed to the desired second and third lines. The suggested work around is:

```
ax = Axis()
push!(ax, Plots.Linear(x0,y0), style="forget plot")
push!(ax, Plots.Linear(x1,y1), legendentry="leg1")
push!(ax, Plots.Linear(x2,y2), legendentry="leg2")
```
Would it be possible to make "forget plot" a default option?

**Comment by mykelk** [comment]
I think `forget plot` might not be what we want. I'll take this one on, after it is working in Julia 1.0, which should be by tomorrow.

**Comment by mykelk** [comment]
Yeah, `forget plot` is not what we want. It will leave the plot out of the legend (which is good), but it won't advance the cycle list. I think we probably need to go about handling legends differently, perhaps with the `\legend` command, which allows us to add empty legends as mentioned [here](https://tex.stackexchange.com/questions/14506/pgfplots-prevent-single-plot-from-being-listed-in-legend). Right now, the implementation uses the `\addlegendentry` command.

**Comment by mossr** [comment]
I submitted a PR #153 based on code Mykel passed along to me and got `\legend{}` working nicely. We can now handle the MWE that Kunal posted (and all examples in the Jupyter notebook passed):
```julia
using PGFPlots
x0,y0 = rand(10), rand(10)
x1,y1 = 1:10, 1:10
x2,y2 = 10:-1:1, 1:10
ax = Axis()
push!(ax, Plots.Linear(x0,y0))
push!(ax, Plots.Linear(x1,y1,legendentry="leg1"))
push!(ax, Plots.Linear(x2,y2,legendentry="leg2"))
ax
```
