### ISSUE TITLE
Smith Charts

### ISSUE THREAD

**Issue by kiranshila** [JuliaTeX/PGFPlots.jl#117]
I am looking to add support for plotting with Smith Charts to PGFPlots as shown in 5.8 in the PGFPlots manual.

```latex
\begin{tikzpicture}[]
% First, the Admittance chart:
\begin{smithchart}[
title=Impedance and Admittance Smith Chart,
smithchart mirrored,
xticklabel shift=-19pt,
grid style={blue},
ticklabel style={blue},
yticklabel around circle,
]
\end{smithchart}
% Second, overlay the impedance chart:
\begin{smithchart}[
show origin,
grid style={red},
ticklabel style={red},
yticklabel around circle*,
]
\addplot+[black,mark=o,only marks,point meta=explicit symbolic,nodes near coords]
coordinates {
(0.2,0.2) [(2)]
(1,0.2) [(1)]
};
\addplot+[black,no marks,domain=0.2:1] {0.2};
\addplot+[black,mark=o,only marks,point meta=explicit symbolic,nodes near coords]
coordinates{
(0.2,0.5) [(3)]
};
\end{smithchart}
\end{tikzpicture}
```

I can start working on it myself and submit a pull request if I get a little guidance on the best way to proceed.

Thanks!

**Comment by mykelk** [comment]
Great! You can base it off of `Plots.Scatter`. You would define a type like
```julia
mutable struct SmithChart <: Plot
```
and add the relevant fields. Then provide functions similar to those associated with `Scatter`. Make sure you update the documentation notebook so that folks can know how to use it.

**Comment by kiranshila** [comment]
Sounds good! Great work by the way, this will really round out a nice RF/Microwave engineering library I'm writing.
