### ISSUE TITLE
plots not displayed in Jupyter notebook

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaTeX/PGFPlots.jl#123]
In the Jupiter notebook, 
```julia
using PGFPlots
x = [1,2,3]
y = [2,4,1]
plot(x, y)
```
produces the text output
```julia
TikzPictures.TikzPicture("\\begin{axis}\\addplot+ coordinates {\n(1, 2)\n(2, 4)\n(3, 1)\n};\n\\end{axis}\n", ",\nscale=1.3", "\\usepackage{pgfplots}\n\\pgfplotsset{compat=newest}\n\\pgfplotsset{every axis legend/.append style={%\ncells={anchor=west}}\n}\n\\usepgfplotslibrary{polar}\n\\usetikzlibrary{arrows}\n\\tikzset{>=stealth'}\n\n\\usepackage{fourier}", true)
```
and no figure is generated.

```julia 
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by mykelk** [comment]
This seems to work for me:
![image](https://user-images.githubusercontent.com/6294079/64085756-6d9d9180-cce9-11e9-9fa1-74524164b3bd.png)

What do you get when you run `;lualatex`?

**Comment by AshtonSBradley** [comment]
almost the same thing:

<img width="486" alt="Screen Shot 2019-09-02 at 2 04 27 PM" src="https://user-images.githubusercontent.com/24194258/64086142-99bd1f00-cd8a-11e9-9299-c460cc82a83d.png">

**Comment by mykelk** [comment]
Do you also get this?
![image](https://user-images.githubusercontent.com/6294079/64135681-cd567400-cd9f-11e9-95ab-d522c8926b19.png)

Also, do other plots (e.g. from Plots.jl) show up in your Jupyter notebooks?

**Comment by AshtonSBradley** [comment]
ok, I don't know what changed, but I think a restart of Julia has fixed it. sorry for the noise, it seems to be working fine!
