### ISSUE TITLE
%  - Percent in label

### ISSUE THREAD

**Issue by holgerteichgraeber** [JuliaTeX/PGFPlots.jl#133]
Hi, 
I am trying to have the `%` sign in a label. However, I do not get the desired result:
```
using Plots
pgfplots()
using LaTeXStrings
plot(ylabel="test [%]")
```
My y label reads the following 
` test [draw opacity = 0.1, line width =0.5, solid `

Using `\%` gives an error: `syntax: invalid escape sequence`.

What do you recommend? 
Thank you already in advance
Holger

**Comment by DilumAluthge** [comment]
Have you tried `\\%`

**Comment by holgerteichgraeber** [comment]
Nice, that works, thank you!
