### ISSUE TITLE
How to add legends to Plots.Histogram

### ISSUE THREAD

**Issue by raunakbh92** [JuliaTeX/PGFPlots.jl#135]
I am placing multiple histograms on a `PGFPlots.Axis` and was wondering how to add legends to the histograms. I do not see a `legendentry` kwarg in the call to `PGFPlots.Plots.Histogram` so wanted to ask if there was an alternative way to add legends.

**Comment by tawheeler** [comment]
PGFPlots.jl generates pgfplots code under the hood. You can see what it generates by saving your output to a .tex file. Any time it is unclear how to do something, figure out how to do it in pgfplots tex first.

[It looks like all you need is a legend entry](https://tex.stackexchange.com/questions/252418/how-to-make-a-nice-legend-for-a-histogram-with-pgfplots). That is,
```
\legend{histogram 1}
```
after your plot command.

You can generate this by including a `Plots.Command(raw"\legend{histogram 1}")` in the list of plots you include in the axis.

Cheers!

**Comment by raunakbh92** [comment]
Thank you so much for the response. I tried the following but did not seem to work. 

```julia
using PGFPlots
a = rand(100)
pa= PGFPlots.Plots.Histogram(a,bins=20,density=true)
PGFPlots.Plots.Command(raw"\legend{histogram a}")
PGFPlots.save("testhist.svg",a)
```
The legend does not show up. Having never used the `Plots.Command` functionality before, I may be doing it completely wrong.

**Comment by mykelk** [comment]
The histogram and the command need to be in the same Axis. See example here:
https://nbviewer.jupyter.org/github/JuliaTeX/PGFPlots.jl/blob/master/doc/PGFPlots.ipynb

**Comment by raunakbh92** [comment]
That worked! Thank you so much for your help!
