### ISSUE TITLE
Significant Figures

### ISSUE THREAD

**Issue by Bebotron** [JuliaTeX/PGFPlots.jl#155]
I couldn't find this anywhere in the examples notebook. I'm trying to manipulate the number of significant figures on my axis ticks.

I have the following data
```Julia
julia> data
10×2 Array{Float64,2}:
  10.0  0.986932
  20.0  0.991782
  30.0  0.993552
  40.0  0.994498
  50.0  0.995099
  60.0  0.995522
  70.0  0.995839
  80.0  0.996087
  90.0  0.996287
 100.0  0.996454
```
And I'm running `Plots.Scatter(data[:,1], data[:,2])`, this produces the following plot

![test](https://user-images.githubusercontent.com/24438203/92297951-a4f8dc80-ef01-11ea-9f92-5f9e8adf436d.png)

This y-axis is completely pointless, and I can't find how to fix it (show 3 significant figures)

**Comment by mossr** [comment]
This can be done through the `style` keyword of `Axis` and using standard pgfplots settings:
```julia
Axis(Plots.Scatter(data[:,1], data[:,2]), style="yticklabel style={/pgf/number format/precision=3}")
```

![image](https://user-images.githubusercontent.com/1592413/107297720-c8800000-6a28-11eb-8891-13397d7604dd.png)


As a future reference, there are a lot of customizable things you can do purely in pgfplots that may not have a direct keyword in PGFPlots.jl, and we use the `style` option as a somewhat catch-all.

Here's more information about pgfplot precision: https://tex.stackexchange.com/questions/220969/pgfplots-significant-figures
