### ISSUE TITLE
How to left assign the title

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaTeX/PGFPlots.jl#160]
Hey all, per this thread: https://stackoverflow.com/questions/64717785/title-left-alignment-with-pgfplots-in-julia/64845779?noredirect=1#comment114688630_64845779 how can I left alight the title of my plot?

**Comment by mirkobunse** [comment]
I replied with a specific and a general answer.

**Comment by mykelk** [comment]
Thanks @mirkobunse !
