### ISSUE TITLE
Allow to disable spines

### ISSUE THREAD

**Issue by cristobaltapia** [JuliaTeX/PGFPlots.jl#164]
Hi, I was looking through the documentation but could not find this. Would it be possible to implement a function to disable specific spines of the axis? That would be very useful.

Thanks!

**Comment by mykelk** [comment]
Are you looking for something like this?
https://tex.stackexchange.com/questions/11107/dropped-spines-in-pgfplot
You can do this by passing the appropriate pgfplots commands to the `style` argument.

**Comment by cristobaltapia** [comment]
Yes, exactly. Thank you! I am new to this package and was not aware of that.
