### ISSUE TITLE
PGFPlots not compatibele with latest interpolations.jl  

### ISSUE THREAD

**Issue by mvanels** [JuliaTeX/PGFPlots.jl#167]
Just installed PGFPlots.jl however i had to pin back the interpolation.jl to v12.

[printout.txt](https://github.com/JuliaTeX/PGFPlots.jl/files/6049318/printout.txt)

**Comment by mykelk** [comment]
The [travis build](https://travis-ci.org/github/JuliaTeX/PGFPlots.jl/jobs/758016798) and my local install does not seem to have this issue. In both cases, we're running PGFPlots v3.3.6 and Interpolations v0.13.1 without any issue.

**Comment by mvanels** [comment]
oke strange, well I cant argue with that. maybe its a Windows issue. Working with the tufte algorithms book template btw I really like it, thanks for sharing.

**Comment by mykelk** [comment]
My local install is on Windows and it works without any issues. Glad you like the template!
