### ISSUE TITLE
Something weird happening

### ISSUE THREAD

**Issue by chelseas** [JuliaTeX/PGFPlots.jl#174]
When I
```
using PGFPlots
```

today:

┌ Info: Precompiling PGFPlots [3b7a836e-365b-5785-a47d-02c71176b4aa]
└ @ Base loading.jl:1278
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for ImageTransformations [02fcd773-0e25-5acc-982a-7f6622650795]
│   exception = Required dependency Rotations [6038ab10-8711-5258-84ad-4b1120ba62dc] failed to load from a cache file.
└ @ Base loading.jl:1042
┌ Warning: Module ImageTransformations with build ID 1161969914684332 is missing from the cache.
│ This may mean ImageTransformations [02fcd773-0e25-5acc-982a-7f6622650795] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1017
WARNING: could not import TikzPictures.@L_mstr into PGFPlots
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for PGFPlots [3b7a836e-365b-5785-a47d-02c71176b4aa]
│   exception = ErrorException("Required dependency ImageContrastAdjustment [f332f351-ec65-5f6a-b3d1-319c6670881a] failed to load from a cache file.")
└ @ Base loading.jl:1042
WARNING: could not import TikzPictures.@L_mstr into PGFPlots

**Comment by mykelk** [comment]
Can you confirm which version of PGFPlots you're using? If you can include the output of `] st`, then we can look into it.

**Comment by chelseas** [comment]
[3b7a836e] PGFPlots v3.3.3

**Comment by mykelk** [comment]
Can you try out 3.4.0?
