### ISSUE TITLE
xtick=data

### ISSUE THREAD

**Issue by chelseas** [JuliaTeX/PGFPlots.jl#175]
I want to be able to use this pgfplots option: 
https://tex.stackexchange.com/questions/47345/specify-the-step-of-pgfplots-axis

xtick=data

is there a hack i can use to make this happen?

**Comment by chelseas** [comment]
e.g. like 

Axis(...., other_plot_options="xtick=data, ytick=data")

**Comment by mykelk** [comment]
It would be `Axis(..., style="xtick=data")`.

**Comment by chelseas** [comment]
thanks! hm....only seems to put ticks for the first line in the plot....
![image](https://user-images.githubusercontent.com/14879690/123026343-d9eef680-d390-11eb-9373-4d0b5852d98c.png)

**Comment by tawheeler** [comment]
Apparently, when you use xtick=data, only the first \addplot command is used to determine the tick positions. To get both tick labels, use xtick={A,B}.

**Comment by chelseas** [comment]
I ended up specifying:
```
xtickten={1,2,3}
```
which actually brought back the x-axis minor grid lines, which I liked.
