### ISSUE TITLE
Add `xtick` and `ytick` in `Axis` 

### ISSUE THREAD

**Issue by wujinq** [JuliaTeX/PGFPlots.jl#184]
Sometimes we need to change the `xtick` option, for example in [this SE question](https://tex.stackexchange.com/questions/100040/how-to-omit-non-integer-x-axis-ticks-in-pgfplots). However, currently `xtick` is not an optional argument (` MethodError: no method matching Axis(::Array{PGFPlots.Plots.Plot,1}; xlabel=L"$k$", xticks=0:4)`).
I suggest adding this as an optional argument to `Axis` function.

**Comment by mirkobunse** [comment]
Just use the `style` argument

```julia
Axis(...; style="xtick={0,1,2,3,4}")
```

and see the other discussions if you need more details: #42 #88 #175

**Comment by wujinq** [comment]
Thanks for you answer!
