### ISSUE TITLE
Failure to precompile due to Tectonic issue

### ISSUE THREAD

**Issue by nskh** [JuliaTeX/PGFPlots.jl#186]
Hi there, I'm having issues precompiling PGFPlots due to an issue with Tectonic https://github.com/MichaelHatherly/Tectonic.jl/issues/13, which breaks precompiling on M1 Macs until an upstream tectonic issue is resolved. This is the same problem as in TikzPictures: https://github.com/JuliaTeX/TikzPictures.jl/issues/82

Is this dependency required? Is there any known workaround for M1 machines?

**Comment by mykelk** [comment]
If you have latex installed on your machine, this dependency isn't required. @dylan-asmar is working on a resolution. This will require changing only TikzPictures.

**Comment by dylan-asmar** [comment]
TikzPictures was just updated to v3.5.0 which supports Apple silicon (M1/M2). After ensuring I had the v3.5.0 TikzPictures, I was able to precompile and use PGFPlots on an M1 system with no issues.

**Comment by nskh** [comment]
Great, thanks! This should work for me.
