### ISSUE TITLE
MethodError in Atom

### ISSUE THREAD

**Issue by mykelk** [JuliaTeX/PGFPlots.jl#68]
In Atom, if I run something like this:
```julia
using PGFPlots
plot(rand(3), rand(3))
```
I get this:
```
ERROR (unhandled task failure): MethodError: objects of type Array{Any,1} are not callable
Use square brackets [] for indexing an Array.
 in macro expansion at /home/mykel/.julia/v0.5/Atom/src/comm.jl:64 [inlined]
 in (::Atom.##14#17)() at ./event.jl:68
```

**Comment by tawheeler** [comment]
The Atom/src/comm.jl:64 line isn't particularly illuminating. It is a try-catch where they print out error messages.
The same code does not cause problems outside of Atom for me.

**Comment by mykelk** [comment]
Yeah, no problems outside of Atom for me.

**Comment by jzazo** [comment]
Does not give error for me at this time. Maybe it has been fixed and issue can be closed?

**Comment by mykelk** [comment]
Yep, it works now.
