### ISSUE TITLE
matrix plot

### ISSUE THREAD

**Issue by hofmannmartin** [JuliaTeX/PGFPlots.jl#73]
A new feature of PGFPlots v1.13 is the new `matrix plot*` (see section 4.6.12 of the manual). It would be great if this new feature would make it into the PGFPlots package as this would allow to create pure vector graphics when plotting 2D functions, histograms or heat maps.

**Comment by AnkurD** [comment]
If no one else is working on this, I'd like to help contribute this functionality, specifically for use as heatmaps.

**Comment by mykelk** [comment]
@AnkurD Yay! That would be awesome! Thanks!

**Comment by mykelk** [comment]
This has now been implemented.
