### ISSUE TITLE
Error using Plots.Image

### ISSUE THREAD

**Issue by rcnlee** [JuliaTeX/PGFPlots.jl#87]
```Julia
julia> using PGFPlots

julia> f=(x,y)->x*exp(-x^2-y^2)
(::#1) (generic function with 1 method)

julia> p=Plots.Image(f,(-2.0,2.0),(-2.0,2.0),colormap=ColorMaps.Distinguishable(3))
PGFPlots.Plots.Image("tmp_10000000000001.png", -2.0, 2.0, -2.0, 2.0, -0.42870694108441587, 0.42870694108441587, true, PGFPlots.ColorMaps.RGBArrayMap(ColorTypes.RGB{Float64}[RGB{Float64}(0.0,0.0,0.0), RGB{Float64}(1.0,1.0,0.384314), RGB{Float64}(1.0,0.623529,1.0)], 0x0000000000000000), nothing)

julia> save("plot.pdf",p)
! error:  (file tmp_10000000000001.png) (pdf backend): internal error: unknown i
mage type
!  ==> Fatal error occurred, no output PDF file produced!
ERROR: LaTeX error
Stacktrace:
 [1] save(::TikzPictures.PDF, ::TikzPictures.TikzPicture) at /Users/rlee18/.julia/v0.6/TikzPictures/src/TikzPictures.jl:210
 [2] #save#43(::Bool, ::Function, ::String, ::PGFPlots.Plots.Image) at /Users/rlee18/.julia/v0.6/PGFPlots/src/PGFPlots.jl:749
 [3] save(::String, ::PGFPlots.Plots.Image) at /Users/rlee18/.julia/v0.6/PGFPlots/src/PGFPlots.jl:746
```

The generated png file seems to be corrupted.  It has size, but doesn't open.

**Comment by mykelk** [comment]
Strange. I'm able to reproduce this and get the same error. However, if I run it in a Julia notebook, the plot looks just fine.

**Comment by rcnlee** [comment]
Weird.  It doesn't work for me there either.  IJulia is where I first encountered the error, actually.

Does the PNG open correctly for you?

**Comment by mykelk** [comment]
I just did a `Pkg.update()` and it works fine for me now. How about you?

**Comment by rcnlee** [comment]
I'm still seeing the problem after an update.  What versions are you using?
Here's mine:
```julia
julia> [p[x] for x in ["PGFPlots","TikzPictures","Images","ImageMagick","FileIO"]]
5-element Array{VersionNumber,1}:
 v"2.2.1"
 v"1.2.0"
 v"0.12.0"
 v"0.5.0"
 v"0.6.1"
```

**Comment by rcnlee** [comment]
It works now.  I did a clean install of Julia 0.6.2 and PGFPlots 2.2.2.

**Comment by parachutel** [comment]
Same problem here. Could you please provide more details about how to solve the problem? @rcnlee thanks!

**Comment by rcnlee** [comment]
I think the problem was in one of the dependent packages, which got fixed later on.  It worked after I did a clean install of Julia, fresh install of all the packages and PGFPlots.jl to 2.2.2.  I tried playing around with pinning/freeing different versions and couldn't get it to work.  Reinstalling worked though.

**Comment by mykelk** [comment]
I think this has to do with ImageMagick.jl, which is a dependency of Images.jl. Does anyone know why (apparently I) added ImageMagick to REQUIRE?

**Comment by tawheeler** [comment]
To ensure that ImageMagick is installed so an svg-related system call works?

**Comment by mykelk** [comment]
Doesn't having Images.jl in REQUIRE automatically install it? (Also, I think it is only used for writing PNGs. The PDF2SVG is a system call.)

**Comment by mykelk** [comment]
I'm having issues on Julia 1.0 with PNGs of zero size being generated on Windows.

**Comment by mykelk** [comment]
This seems to be resolved now.
