### ISSUE TITLE
Concise conversion to .tex

### ISSUE THREAD

**Issue by jzazo** [JuliaTeX/PGFPlots.jl#99]
Hi! I tried this backend to output `.tex` files, but the exported file is always very lengthy for very simple plots. It normally includes lots of options that I had not specified, and makes the `.tex` file difficult to edit. `matlab2tikz` for instance used more concise translations in simple graphs and was very concise. Is it possible to simplify the output file? Thanks.

EDIT: OK, the culprit seems to be Plots.jl, which exports lots of attributes for very simple plots. 
Sorry if this is not the appropriate place to open this issue, but is there a way to limit the list of the exported attributes?

**Comment by mykelk** [comment]
Yeah, that would require modifying Plots.jl. PGFPlots.jl when used on its own only sets options that you specify.

**Comment by jzazo** [comment]
Thank you.
